// <auto-generated />
using Medq.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medq.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MedqDbContext))]
    [Migration("20250827074726_SeedV1")]
    partial class SeedV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Medq.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Cityville",
                            Name = "Downtown Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Townsville",
                            Name = "Uptown Medical Center"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St, Suburbia",
                            Name = "Suburban Family Clinic"
                        });
                });

            modelBuilder.Entity("Medq.Domain.Entities.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpenNow")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Health St, Cityville",
                            Name = "City Pharmacy",
                            OpenNow = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "200 Wellness Ave, Townsville",
                            Name = "Town Drugstore",
                            OpenNow = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 Care Blvd, Suburbia",
                            Name = "Suburbia Meds",
                            OpenNow = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
